# Hei Njål
# ***I LOVE COCK***

In [134]:
print('U lost bbygurl?')

U lost bbygurl?

Importing our dataset

In [135]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/england-premier-league-matches-2018-to-2019-stats.csv")

Analyszing features

In [136]:
df.head()

odds_columns = [col for col in df.columns if 'odds' in col.lower()]
df[odds_columns].sample()
prematch_columns = [col for col in df.columns if 'pre' in col.lower() and 'match' in col.lower()]
df[prematch_columns].sample()
null_columns = [col for col in df.columns if (df[col] == 0).all()]
df[null_columns].head()
not_completed = [col for col in df.columns if (df['status'] != 'complete').any()]
print(not_completed)

[]

Data cleaning

In [137]:

#Remove all columns in the dataset that include odds. 
df_filtered = df.drop(columns = odds_columns)

#The first match 2 matches of the season has no 'pre-match' content, but are valued at 0, which could mess with this feature
df_filtered.loc[df['Game Week'] <= 2, prematch_columns] = np.nan


df_filtered.sample(5)

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,over_25_percentage_pre_match,over_35_percentage_pre_match,over_45_percentage_pre_match,over_15_HT_FHG_percentage_pre_match,over_05_HT_FHG_percentage_pre_match,over_15_2HG_percentage_pre_match,over_05_2HG_percentage_pre_match,average_corners_per_match_pre_match,average_cards_per_match_pre_match,stadium_name
237,1548877500,Jan 30 2019 - 7:45pm,complete,28339,Southampton,Crystal Palace,Andre Marriner,24,1.00,1.08,...,66.0,39.0,17.0,22.0,61.0,61.0,74.0,9.02,4.72,St. Mary's Stadium (Southampton- Hampshire)
353,1556373600,Apr 27 2019 - 2:00pm,complete,23822,Fulham,Cardiff City,Chris Kavanagh,36,1.06,0.65,...,47.0,24.0,21.0,33.0,71.0,44.0,77.0,9.12,3.94,Craven Cottage (London)
201,1546354800,Jan 01 2019 - 3:00pm,complete,59887,Arsenal,Fulham,Graham Scott,21,2.30,0.20,...,50.0,40.0,15.0,30.0,70.0,60.0,90.0,8.60,4.00,Emirates Stadium (London)
25,1535214600,Aug 25 2018 - 4:30pm,complete,53294,Liverpool,Brighton & Hove Albion,Chris Kavanagh,3,3.00,0.00,...,50.0,50.0,0.0,50.0,100.0,50.0,100.0,7.00,3.00,Anfield (Liverpool)
67,1538238600,Sep 29 2018 - 4:30pm,complete,40625,Chelsea,Liverpool,Andre Marriner,7,3.00,3.00,...,67.0,34.0,34.0,50.0,84.0,50.0,100.0,10.67,1.67,Stamford Bridge (London)

Feature Importance Testing

Final Feature Selection

In [143]:
selected_features = [
    'Game Week',
    'home_team_name',
    'away_team_name',
    'Pre-Match PPG (Home)',
    'Pre-Match PPG (Away)',
    'home_ppg',
    'away_ppg',
    'Home Team Pre-Match xG',
    'Away Team Pre-Match xG',
    'home_team_goal_count',
    'away_team_goal_count',
    'total_goal_count',
    'home_team_shots_on_target',
    'away_team_shots_on_target',
    'home_team_possession',
    'away_team_possession',
    'average_goals_per_match_pre_match',
]

df_final = df_filtered[selected_features]

df_final.sample(10)
df_final.head()

,Game Week,home_team_name,away_team_name,Pre-Match PPG (Home),Pre-Match PPG (Away),home_ppg,away_ppg,Home Team Pre-Match xG,Away Team Pre-Match xG,home_team_goal_count,away_team_goal_count,total_goal_count,home_team_shots_on_target,away_team_shots_on_target,home_team_possession,away_team_possession,average_goals_per_match_pre_match
0,1,Manchester United,Leicester City,NaN,NaN,1.89,1.32,NaN,NaN,2,1,3,7,5,46,54,NaN
1,1,Newcastle United,Tottenham Hotspur,NaN,NaN,1.32,1.74,NaN,NaN,1,2,3,3,6,40,60,NaN
2,1,AFC Bournemouth,Cardiff City,NaN,NaN,1.53,0.74,NaN,NaN,2,0,2,5,2,62,38,NaN
3,1,Fulham,Crystal Palace,NaN,NaN,1.11,1.53,NaN,NaN,0,2,2,7,11,66,34,NaN
4,1,Huddersfield Town,Chelsea,NaN,NaN,0.47,1.58,NaN,NaN,0,3,3,2,5,37,63,NaN