# Hei Njål
# ***I LOVE COCK***

In [55]:
print('U lost bbygurl?')

U lost bbygurl?

Importing our dataset

In [67]:
import pandas as pd

df = pd.read_csv("../data/england-premier-league-matches-2018-to-2019-stats.csv")

Analyszing features

In [70]:
df.head()

odds_columns = [col for col in df.columns if 'odds' in col]
df[odds_columns].head()
prematch_columns = [col for col in df.columns if 'pre' in col.lower() and 'match' in col.lower()]
df[prematch_columns].head()
null_columns = [col for col in df.columns if (df[col] == 0).any()]
df[null_columns].head()

,home_team_goal_count,away_team_goal_count,total_goal_count,total_goals_at_half_time,home_team_goal_count_half_time,away_team_goal_count_half_time,home_team_corner_count,away_team_corner_count,home_team_yellow_cards,home_team_red_cards,...,home_team_first_half_cards,home_team_second_half_cards,away_team_first_half_cards,away_team_second_half_cards,home_team_shots,home_team_shots_on_target,away_team_shots_on_target,home_team_shots_off_target,away_team_shots_off_target,home_team_fouls
0,2,1,3,1,1,0,2,5,2,0,...,0,2,0,1,8,7,5,1,3,11
1,1,2,3,3,1,2,3,5,2,0,...,0,2,1,1,11,3,6,8,7,11
2,2,0,2,1,1,0,7,4,1,0,...,1,0,1,0,11,5,2,6,5,11
3,0,2,2,1,0,1,5,5,1,0,...,1,0,1,1,11,7,11,4,0,9
4,0,3,3,2,0,2,2,5,2,0,...,1,1,0,1,6,2,5,4,3,9

Data cleaning

In [69]:
#Remove all columns in the dataset that include odds. 
df = df.drop(columns = odds_columns)

#Remove all columns that include Pre-match statistics (all 0 anyways)
df =  df.drop(columns=prematch_columns)
 
df.head()

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,home_ppg,away_ppg,...,away_team_shots_on_target,home_team_shots_off_target,away_team_shots_off_target,home_team_fouls,away_team_fouls,home_team_possession,away_team_possession,team_a_xg,team_b_xg,stadium_name
0,1533927600,Aug 10 2018 - 7:00pm,complete,74439,Manchester United,Leicester City,Andre Marriner,1,1.89,1.32,...,5,1,3,11,8,46,54,1.25,1.46,Old Trafford (Manchester)
1,1533987000,Aug 11 2018 - 11:30am,complete,51749,Newcastle United,Tottenham Hotspur,Martin Atkinson,1,1.32,1.74,...,6,8,7,11,12,40,60,1.18,1.58,St. James' Park (Newcastle upon Tyne)
2,1533996000,Aug 11 2018 - 2:00pm,complete,10353,AFC Bournemouth,Cardiff City,Kevin Friend,1,1.53,0.74,...,2,6,5,11,9,62,38,1.50,0.89,Vitality Stadium (Bournemouth- Dorset)
3,1533996000,Aug 11 2018 - 2:00pm,complete,24821,Fulham,Crystal Palace,Mike Dean,1,1.11,1.53,...,11,4,0,9,11,66,34,1.67,1.81,Craven Cottage (London)
4,1533996000,Aug 11 2018 - 2:00pm,complete,24121,Huddersfield Town,Chelsea,Chris Kavanagh,1,0.47,1.58,...,5,4,3,9,8,37,63,0.90,1.17,John Smith's Stadium (Huddersfield- West Yorks...